name: Build executables
on:
  push:
    branches: [ master, develop, build ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-ubuntu22:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python_versions: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_versions }}
          cache: 'pip'
          architecture: 'x64'

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt --upgrade

      - name: Install apt requirements
        run: | 
          sudo apt update
          sudo apt install libheif1 libheif-dev -y

      - name: Build wheel
        run: | 
          python setup.py bdist_wheel --use-cython

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: cyheif
          path: dist/*.whl


  build-windows-2019:

    runs-on: windows-2019

    strategy:
      matrix:
        python_versions: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_versions }}
          cache: 'pip'
          architecture: 'x64'

      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt --upgrade

      - uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: f93ba152d55e1d243160e690bc302ffe8638358e
          cache-key: vcpkg-py${{ matrix.python_versions }}-f93ba
          cache-restore-keys: vcpkg-py${{ matrix.python_versions }}-
          path: vcpkg

      - name: Build libheif
        run: |
          vcpkg\vcpkg.exe install libheif --triplet x64-windows

      - name: Build wheel
        run: |
          python setup.py bdist_wheel --use-cython

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: cyheif
          path: dist/*.whl
